### ISSUE TITLE
Date::Error in EventsController#create

### ISSUE THREAD

**Issue by beingmattlevy** [fnf-org/TicketBooth#78]
Date::Error in EventsController#create

      ::DateTime.strptime("#{datetime_string.upcase} #{Time.current.strftime('%z')}Z", TIME_FORMAT).to_time

Rails.root: /Users/matt/Sandbox/TicketBooth

Application Trace | Framework Trace | Full Trace
app/helpers/time_helper.rb:19:in `strptime'
app/helpers/time_helper.rb:19:in `to_datetime_from_picker'
app/controllers/events_controller.rb:130:in `block in convert_event_times_for_db'
app/controllers/events_controller.rb:129:in `each'
app/controllers/events_controller.rb:129:in `convert_event_times_for_db'
app/controllers/events_controller.rb:38:in `create'

![Screenshot 2024-04-16 at 12 40 10 PM](https://github.com/fnf-org/TicketBooth/assets/1203197/fb1c9f8c-b193-428e-a249-f232d355c51d)

**Comment by beingmattlevy** [comment]
Will create a test for this now.

**Comment by beingmattlevy** [comment]
Issue was empty strings in event params time fields
