### ISSUE TITLE
unable to request tickets

### ISSUE THREAD

**Issue by beingmattlevy** [fnf-org/TicketBooth#81]
Submit Request button is greyed out and not allowing me to submit a request

http://localhost:5000/events/4/ticket_requests/new

**Comment by beingmattlevy** [comment]
Getting an Uncaught TypeError in the Inspection Console

Uncaught TypeError: popover is not a function
    at application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:6976:7
    at app/javascript/popovers.ts (application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:6983:7)
    at __require (application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:11:50)
    at application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:22462:31
(anonymous) @ application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:6976
app/javascript/popovers.ts @ application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:6983
__require @ application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:11
(anonymous) @ application-484deafe53ca0bdee4c94fabfcc68c5998e01379.js:22462

![Screenshot 2024-04-16 at 4 53 41 PM](https://github.com/fnf-org/TicketBooth/assets/1203197/9758105b-ab8c-43fd-8a3b-2e24f93a6041)
