### ISSUE TITLE
TypeError on console preventing popover

### ISSUE THREAD

**Issue by beingmattlevy** [fnf-org/TicketBooth#83]
application-bdc77ce1…63f88a8f95.js:11764 Uncaught TypeError: popover is not a function
    at application-bdc77ce1…f88a8f95.js:11764:7
    at app/javascript/popovers.ts (application-bdc77ce1…f88a8f95.js:11771:7)
    at __require (application-bdc77ce1…63f88a8f95.js:11:50)
    at application-bdc77ce1…88a8f95.js:22094:31
(anonymous)	@	application-bdc77ce1…63f88a8f95.js:11764
app/javascript/popovers.ts	@	application-bdc77ce1…63f88a8f95.js:11771
![Screenshot 2024-04-17 at 12 22 24 PM](https://github.com/fnf-org/TicketBooth/assets/1203197/ccc7996d-419e-4720-894b-f77f4cf59429)

__require	@	application-bdc77ce1…b5763f88a8f95.js:

**Comment by beingmattlevy** [comment]
This is causing many issues.

**Comment by beingmattlevy** [comment]
Can not reproduce after updates
